In [1]:
import pandas as pd

# Load job descriptions
jobs_df = pd.read_csv("../data/raw/job_descriptions.csv")

print("Job descriptions loaded successfully!")
print("Shape:", jobs_df.shape)
print("\nColumns:")
print(jobs_df.columns.tolist())

Job descriptions loaded successfully!
Shape: (12, 4)

Columns:
['job_id', 'job_title', 'job_description', 'required_skills']

In [2]:
# View the available jobs

jobs_df[
    ["job_id", "job_title", "required_skills"]
]

,job_id,job_title,required_skills
0,J001,AI/ML Engineer,"Python, Machine Learning, Deep Learning, Tenso..."
1,J002,Data Analyst,"SQL, Excel, Power BI, Tableau, Python, Data Vi..."
2,J003,Data Scientist,"Python, Statistics, Machine Learning, Pandas, ..."
3,J004,Software Developer,"Java, C++, Python, Data Structures, Algorithms..."
4,J005,Web Developer,"HTML, CSS, JavaScript, React, Node.js, Git, RE..."
5,J006,Cybersecurity Analyst,"Network Security, Linux, SIEM, Ethical Hacking..."
6,J007,Cloud Engineer,"AWS, Azure, Cloud Computing, Linux, Docker, Ne..."
7,J008,Database Administrator,"SQL, MySQL, PostgreSQL, Oracle, Database Manag..."
8,J009,DevOps Engineer,"Docker, Kubernetes, Jenkins, Git, CI/CD, AWS, ..."
9,J010,Mobile App Developer,"Android, Kotlin, Java, Flutter, Dart, Firebase..."
10,J011,QA/Test Engineer,"Manual Testing, Selenium, Java, Python, JUnit,..."
11,J012,Business Analyst,"SQL, Excel, Power BI, Requirements Analysis, D..."

In [2]:
import pandas as pd

# Load job descriptions
jobs_df = pd.read_csv("../data/raw/job_descriptions.csv")

print("Job descriptions loaded successfully!")
print("Shape:", jobs_df.shape)

Job descriptions loaded successfully!
Shape: (12, 4)

In [3]:
jobs_df["job_text"] = (
    jobs_df["job_title"].fillna("") + " " +
    jobs_df["job_description"].fillna("") + " " +
    jobs_df["required_skills"].fillna("")
)

print("Job text prepared successfully!")
print("Number of job descriptions:", len(jobs_df))

Job text prepared successfully!
Number of job descriptions: 12

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Create a separate vectorizer for job matching
job_vectorizer = TfidfVectorizer(
    stop_words="english"
)

# Convert job descriptions into TF-IDF vectors
job_tfidf_matrix = job_vectorizer.fit_transform(
    jobs_df["job_text"]
)

print("Job TF-IDF transformation completed!")
print("Job TF-IDF matrix shape:", job_tfidf_matrix.shape)

Job TF-IDF transformation completed!
Job TF-IDF matrix shape: (12, 170)

In [7]:
import pandas as pd

# Load the cleaned resume dataset
cleaned_df = pd.read_csv("../data/processed/cleaned_resumes.csv")

print("Cleaned resume dataset loaded successfully!")
print("Shape:", cleaned_df.shape)

Cleaned resume dataset loaded successfully!
Shape: (1200, 4)

In [8]:
from sklearn.metrics.pairwise import cosine_similarity

sample_resume = cleaned_df["cleaned_resume_text"].iloc[0]

resume_vector = job_vectorizer.transform([sample_resume])

similarity_scores = cosine_similarity(
    resume_vector,
    job_tfidf_matrix
)[0]

print("Similarity calculation completed!")
print("Number of job scores:", len(similarity_scores))

Similarity calculation completed!
Number of job scores: 12

In [9]:
# Find the job with the highest similarity score

best_job_index = similarity_scores.argmax()

best_job = jobs_df.iloc[best_job_index]["job_title"]
best_score = similarity_scores[best_job_index]

print("Best Matching Job:", best_job)
print(f"Match Score: {best_score * 100:.2f}%")

Best Matching Job: AI/ML Engineer
Match Score: 62.93%

In [10]:
# Display match scores for all jobs

job_match_results = pd.DataFrame({
    "Job Title": jobs_df["job_title"],
    "Match Score": similarity_scores * 100
})

job_match_results = job_match_results.sort_values(
    by="Match Score",
    ascending=False
).reset_index(drop=True)

job_match_results["Match Score"] = job_match_results["Match Score"].round(2)

job_match_results

                 Job Title  Match Score
0           AI/ML Engineer        62.93
1           Data Scientist        24.97
2         QA/Test Engineer        10.08
3       Software Developer         9.11
4          DevOps Engineer         8.64
5   Database Administrator         3.91
6             Data Analyst         3.12
7    Cybersecurity Analyst         2.85
8     Mobile App Developer         2.66
9            Web Developer         2.56
10          Cloud Engineer         2.03
11        Business Analyst         0.00

In [11]:
# Function to compare resume skills with required job skills

def compare_skills(resume_skills, required_skills):
    resume_skills_lower = {
        skill.lower().strip()
        for skill in resume_skills
    }

    required_skills_list = [
        skill.strip()
        for skill in required_skills.split(",")
    ]

    matching_skills = []
    missing_skills = []

    for skill in required_skills_list:
        if skill.lower() in resume_skills_lower:
            matching_skills.append(skill)
        else:
            missing_skills.append(skill)

    return matching_skills, missing_skills


print("Skill comparison function created successfully!")

Skill comparison function created successfully!

In [13]:
import re

# Skill dictionary
job_skills = {
    "AI/ML Engineer": [
        "Python", "Machine Learning", "Deep Learning",
        "TensorFlow", "PyTorch", "NLP",
        "NumPy", "Pandas", "Scikit-learn"
    ],
    "Data Analyst": [
        "SQL", "Excel", "Power BI", "Tableau",
        "Python", "Data Visualization", "Statistics", "Pandas"
    ],
    "Data Scientist": [
        "Python", "Statistics", "Machine Learning",
        "Pandas", "NumPy", "Scikit-learn",
        "SQL", "Data Visualization"
    ],
    "Software Developer": [
        "Java", "C++", "Python", "Data Structures",
        "Algorithms", "OOP", "Git", "SQL"
    ],
    "Web Developer": [
        "HTML", "CSS", "JavaScript", "React",
        "Node.js", "Git", "REST API", "Web Development"
    ],
    "Cybersecurity Analyst": [
        "Network Security", "Linux", "SIEM",
        "Ethical Hacking", "Cryptography", "Python",
        "Cybersecurity", "Vulnerability Assessment"
    ],
    "Cloud Engineer": [
        "AWS", "Azure", "Cloud Computing", "Linux",
        "Docker", "Networking", "Terraform", "Cloud Security"
    ],
    "Database Administrator": [
        "SQL", "MySQL", "PostgreSQL", "Oracle",
        "Database Management", "Linux",
        "Database Security", "Backup"
    ],
    "DevOps Engineer": [
        "Docker", "Kubernetes", "Jenkins", "Git",
        "CI/CD", "AWS", "Linux", "Terraform"
    ],
    "Mobile App Developer": [
        "Android", "Kotlin", "Java", "Flutter",
        "Dart", "Firebase", "Mobile Development", "Git"
    ],
    "QA/Test Engineer": [
        "Manual Testing", "Selenium", "Java", "Python",
        "JUnit", "Test Automation", "API Testing", "Software Testing"
    ],
    "Business Analyst": [
        "SQL", "Excel", "Power BI", "Requirements Analysis",
        "Documentation", "Agile", "Business Analysis", "Data Analysis"
    ]
}

# Skill extraction function
def extract_skills(text, skill_dictionary):
    text = text.lower()
    extracted_skills = []

    for category_skills in skill_dictionary.values():
        for skill in category_skills:
            pattern = r"\b" + re.escape(skill.lower()) + r"\b"

            if re.search(pattern, text):
                extracted_skills.append(skill)

    return list(dict.fromkeys(extracted_skills))


print("Skill extraction function loaded successfully!")

Skill extraction function loaded successfully!

In [14]:
# Get skills from the first resume
resume_skills = extract_skills(
    cleaned_df["cleaned_resume_text"].iloc[0],
    job_skills
)

# Get required skills for the best-matching job
required_skills = jobs_df.iloc[best_job_index]["required_skills"]

# Compare skills
matching_skills, missing_skills = compare_skills(
    resume_skills,
    required_skills
)

print("Best Matching Job:", best_job)

print("\nMatching Skills:")
print(matching_skills)

print("\nMissing Skills:")
print(missing_skills)

Best Matching Job: AI/ML Engineer

Matching Skills:
['Python', 'Machine Learning', 'PyTorch', 'NLP', 'NumPy']

Missing Skills:
['Deep Learning', 'TensorFlow', 'Pandas', 'Scikit-learn']

In [15]:
# Generate skill recommendations from missing skills

def recommend_skills(missing_skills, max_recommendations=5):
    """
    Recommend missing skills that can improve the resume's
    match with the selected job.
    """
    
    recommendations = missing_skills[:max_recommendations]

    return recommendations


recommended_skills = recommend_skills(missing_skills)

print("Recommended Skills:")
print(recommended_skills)

Recommended Skills:
['Deep Learning', 'TensorFlow', 'Pandas', 'Scikit-learn']

In [16]:
# Save the prepared job descriptions

jobs_output_path = "../data/processed/processed_job_descriptions.csv"

jobs_df.to_csv(jobs_output_path, index=False)

print("Processed job descriptions saved successfully!")
print("Location:", jobs_output_path)

Processed job descriptions saved successfully!
Location: ../data/processed/processed_job_descriptions.csv

In [17]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent / "src"))

from job_matcher import calculate_job_matches

print("Job matcher imported successfully!")

Job matcher imported successfully!

In [18]:
sample_resume = """
Python machine learning NLP Pandas NumPy
TensorFlow Scikit-learn
"""

match_results = calculate_job_matches(
    sample_resume,
    jobs_df
)

print(match_results)

                 Job Title  Match Score
0           AI/ML Engineer        65.87
1           Data Scientist        39.14
2             Data Analyst         7.60
3       Software Developer         2.81
4    Cybersecurity Analyst         2.47
5         QA/Test Engineer         1.96
6           Cloud Engineer         0.00
7            Web Developer         0.00
8   Database Administrator         0.00
9          DevOps Engineer         0.00
10    Mobile App Developer         0.00
11        Business Analyst         0.00